### ISSUE TITLE
Repeated paragraph

### ISSUE THREAD

**Issue by huyiwen** [cascip/awesome-auto-alignment#4]
![image](https://github.com/cascip/awesome-auto-alignment/assets/5737212/9b0ef594-0839-4b0d-b180-da51ca2ae8dc)

**Comment by huyiwen** [comment]
![image](https://github.com/cascip/awesome-auto-alignment/assets/5737212/75c9a277-49d5-454e-aa18-5c6d1789d7cd)

small typos ("format" alignment)

**Comment by c-box** [comment]
You're very welcome for pointing out these issues! We will address them all in the next update. Thank you again for your assistance!

**Comment by luxinyu1** [comment]
Hi @huyiwen, we provide a nightly updated version of our paper. You can check it out [here](https://luxinyu-oss.oss-cn-beijing.aliyuncs.com/automated_alignment/AutoAlign.pdf). Apologies for any inconvenience.
