### ISSUE TITLE
Bring your attention to our work

### ISSUE THREAD

**Issue by youganglyu** [cascip/awesome-auto-alignment#6]
Hi authors,

I have read your paper ''Towards Scalable Automated Alignment of LLMs: A Survey'', very informative, congrats!

We have recently published work in the direction of weak-to-strong alignment
''MACPO: Weak-to-Strong Alignment via Multi-Agent Contrastive Preference Optimization'' (https://arxiv.org/pdf/2410.07672)

In this work, we facilitate weak teachers and strong students to learn from each other by iteratively reinforcing unfamiliar positive behaviors and penalizing familiar negative ones to achieve weak-to-strong alignment. 

We think this work is very relevant to the content of your survey and we have cited your paper in our paper. We really appreciate if you could mention our work in your next version. Congratulations on your work again!

Best wishes,
Yougang

**Comment by luxinyu1** [comment]
Thanks. We have added your paper to the paper list and will consider adding this to the next version of the survey.
